# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM 
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: https://registry.npmjs.org/
      - name: 'Install dependencies'
      - run: npm ci
      - name: 'Test Package'
      - run: npm run test
      - name: 'Publish package'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
